include:
  - path: ./docker-compose.elk.yml
  - path: ./docker-compose.monitoring.yml
services:
  nginx:
    build: ../nginx
    image: nginx
    logging:
      driver: "json-file"
      options:
        tag: "nginx"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ../nginx/certs:/etc/ssl:ro
    env_file:
      - ../env/nginx.env
    networks:
      - public_net
      - internal_net
      - monitoring_net
      - elk_net
    depends_on:
      - backend_api
      - front_end
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always

  front_end:
    build:
      context: ../../netpong-app
      dockerfile: ../infra/frontend/Dockerfile
    image: frontend
    networks:
      - internal_net
    restart: always

  backend_api:
    build:
      context: ../../backend_srcs
      dockerfile: ../infra/backend/Dockerfile
    image: backend_api
    logging:
      driver: "json-file"
      options:
        tag: "backend_api"
    env_file:
      - ../env/backend.env
    volumes:
      - avatar_data:/app/uploads/avatars
    networks:
      - internal_net
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always


  database:
    image: postgres:17
    env_file:
      - ../env/database.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  
  status_service:
    build: ../status
    image: status_service
    container_name: status_service
    networks:
      - internal_net
      - monitoring_net
    restart: always
  
  backup:
    build: ../backup
    env_file:
      - ../env/backup.env
    volumes:
      - /opt/netpong/backups/postgres:/local-backups
    networks:
      - internal_net
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
  avatar_data:

networks:
  public_net:
    name: public_net
    driver: bridge
  internal_net:
    name: internal_net
    driver: bridge
  monitoring_net:
    driver: bridge
    name: monitoring_net
  elk_net:
    driver: bridge
    name: elk_net
