input {
  file {
    path => "/var/log/docker_logs/**/*.log"
    start_position => "end"
    sincedb_path => "/usr/share/logstash/data/sincedb"
    codec => "json"
  }
}

filter {

  if [attrs][tag] == "logstash-internal" {
    drop { }
  }

  if [log] {
    mutate {
      rename => { "log" => "message" }
    }
  }

  date {
    match => [ "time", "ISO8601" ]
    target => "@timestamp"
  }

  if [attrs][tag] == "nginx" {
    mutate { add_field => { "service" => "nginx" } }
  } else if [attrs][tag] == "backend_api" {
    mutate { add_field => { "service" => "backend" } }
  } else {
    mutate { add_field => { "service" => "system" } }
  }

  if [service] == "nginx" {

    grok {
      match => {
        "message" => '%{IPORHOST:client_ip} - %{DATA:user} \[%{HTTPDATE:nginx_time}\] "%{WORD:method} %{URIPATHPARAM:path} HTTP/%{NUMBER:http_version}" %{NUMBER:status} %{NUMBER:bytes} "%{DATA:referrer}" "%{DATA:user_agent}"'
      }
      tag_on_failure => ["nginx_grok_failed"]
    }

    date {
      match => [ "nginx_time", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
      remove_field => ["nginx_time"]
    }
  }

  if [service] == "nginx" and [client_ip] and [client_ip] != "-" {
    geoip {
      source => "client_ip"
      target => "geoip"
    }
  }

  if [service] == "backend" {
    grok {
      match => {
        "message" => "\[%{DATA:app}\] %{NUMBER:pid} - %{DATA:log_time} %{WORD:level} \[%{DATA:context}\] %{GREEDYDATA:backend_message}"
      }
      tag_on_failure => ["backend_grok_failed"]
    }

    mutate {
      lowercase => ["level"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "appdata"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }
}
