input {
  file {
    path => "/var/log/docker_logs/**/*.log"
    start_position => "end"
    sincedb_path => "/usr/share/logstash/data/sincedb"
    codec => "json"
  }
}

filter {

  if [attrs][tag] == "logstash-internal" {
    drop { }
  }

  if [log] {
    mutate {
      rename => { "log" => "message" }
    }
  }

  date {
    match => [ "time", "ISO8601" ]
    target => "@timestamp"
  }

  if [attrs][tag] == "nginx" {
    mutate { add_field => { "service" => "nginx" } }
  } else if [attrs][tag] == "backend_api" {
    mutate { add_field => { "service" => "backend" } }
  } else {
    mutate { add_field => { "service" => "system" } }
  }

  if [service] == "nginx" {

    grok {
      match => {
        "message" => '%{IPORHOST:client_ip} - %{DATA:user} \[%{HTTPDATE:nginx_time}\] "%{WORD:method} %{URIPATHPARAM:path} HTTP/%{NUMBER:http_version}" %{NUMBER:status} %{NUMBER:bytes} "%{DATA:referrer}" "%{DATA:user_agent}"'
      }
      tag_on_failure => ["nginx_grok_failed"]
    }

    date {
      match => [ "nginx_time", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
      remove_field => ["nginx_time"]
    }
  }

  if [service] == "nginx" and [client_ip] and [client_ip] != "-" {
    geoip {
      source => "client_ip"
      target => "geoip"
    }
  }

  if [service] == "backend" {
    json {
      source => "message"
      target => "pino"
      skip_on_invalid_json => true
    }

    mutate {
      add_field => {
        "level" => "%{[pino][level]}"
        "msg"   => "%{[pino][msg]}"
      }
    }

    if [pino][context] {
      mutate { add_field => { "context" => "%{[pino][context]}" } }
    }
  }
}

output {
  if [service] == "backend" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "backend-logs-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
    }
  } else if [service] == "nginx" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nginx-logs-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "system-logs-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
    }
  }
}
